# Generated by Django 5.1.2 on 2024-10-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employe',
        ),
    ]
